- name: pinging
  hosts: all  
  vars:  # {{var}} - this is how we print a variable.
    - msg: hello
    - ping: this is pinged.  
  tasks: 
    - name: ping resule
      ansible.builtin.ping: 
        data: pong

    - name: Prints lines of messages
      ansible.builtin.debug:
        msg: 
          - "testing the varialbe concept - {{ping}}"   
          - "testing the varialbe concept - {{msg}}"     
      vars:
        - ping: task level var            
    