- name: how to use shell commands. 
  hosts: all  # mention the group on which we have to do the configuration management.
  # gather_facts: false # by default this will be true. if kept to false then ansible dont gather facts before executing the play.
  vars:  # {{var}} - this is how we reference a variable and global level varaible.
    - msg: hello
    - ping: this is pinged. 

  tasks: 
    - name: ping resule
      ansible.builtin.ping: 
        data: pong

    - name: running a shell
      ansible.builtin.shell: uptime
      register: sheout # this is a varaible where the output of the command execution lies.

    - name: Prints lines of messages
      ansible.builtin.debug:
        msg: 
          - "testing the variable concept - {{sheout.stdout}}" # sheout.stdout -> this is called nested result. weher we would like to see certain part of the output.
      vars: ## task level more precedence than global level.
        - ping: task level var